<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Playground.ImageCrypto</RootNamespace>
    <AssemblyName>ImageCrypto</AssemblyName>
    <ApplicationTitle>图片加密验证</ApplicationTitle>
  </PropertyGroup>
</Project>
